version: "3.7"
services:
  web:
    build:
      context: .
      args:
        is_local: 1
    restart: always
    ports:
      - "3030:3000"
    volumes:
      - .:/usr/local/src
      - /usr/local/src/node_modules
    command: ["npm", "run", "dev"]
