version: "3.7"
services:
  web:
    build:
      context: .
      args:
        is_local: 1
    restart: always
    ports:
      - "3030:30"
    volumes:
      - .:/usr/local/share
      - /node_modules
    command: ["npm", "run", "install-dev"]
